from amplitude_teacher.teacher_dataset import AmplitudeTeacher
from amplitude_teacher.spectral_teacher import compute_amplitudes_pybhpt
from amplitude_teacher.gsn_teacher import compute_amplitudes_gsn
